name: Sync Analytics Cron

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  ping-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |

          response=$(curl -L -s -w "\n%{http_code}" -X GET ${{ secrets.NEXTAUTH_URL }}/api/cron/sync-analytics \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}")


          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "üîç RESPONSE DARI SERVER:"
          echo "$body"
          echo "---------------------"
          echo "Status Code: $http_code"

          if [ "$http_code" -ne 200 ]; then
            echo "‚ùå Error: API returned status $http_code"
            exit 1
          fi
